name: crystalg

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.35.0

    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Deploy document
      uses: peaceiris/actions-gh-pages@v3
      run: crystal docs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs